apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com   # here we run csi driver, so we are using the provisioner ebs.csi 
volumeBindingMode: WaitForFirstConsumer
