apiVersion: v1
kind: Pod
metadata:
  name: jenkinsprivate
spec:
  containers:
  - name: envars-test-container
    image: jagruthi111/master-slave:10    
  imagePullSecrets:
    - name: regcred  # secret name created using below command which contains- credentials of docker ub or any registry like amazon ecr



#creating secrets for pvt repo : kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>
