apiVersion: v1
kind: Pod
metadata:
  name: jenkinsprivate
spec:
  containers:
  - name: envars-test-container
    image: jagruthi111/master-slave:10



#for pvt repo: kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>
