apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resourcequota
  namespace: mynamespace
spec:
  hard:
    pods: "5"
    requests.cpu: "1" 
    requests.memory: "2Gi"
    limits.cpu: "2" 
    limits.memory: "4Gi" 



# Resourceqouta is used to set the boundary for the namespace
# we can limit pods, cpu and memory how much can namespace utilized using resourcequota
#requests.cpu: "1"      - allocated the cpu in namespace
#requests.memory: "2Gi" - allocates the memory in namespace
#limits.cpu: "2"        - allocates the maximum cpu in namespace
#limits.memory: "4Gi"   -  allocates the maximum memory in namespace
