apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myjenkins
  template:
    metadata:
      labels:
        app: myjenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          volumeMounts:
            - name: jenkins-ebs
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-ebs
          persistentVolumeClaim:
          claimName: ebs-claim
